name: 'Chrisjroe '
favicon: null
layout_spectrum: 0.25472
typography_spectrum: 0.46719
title: Chris J Roe
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#b9b9b9'
    - '#d8d8d8'
    - '#6d6d6d'
    - '#292929'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
