layout_spectrum: 0.1680988
color:
  saturation: 0.6233945
  brandStrength: 0.1846794
  lightness: 0.9640172
  rhythmicContrast: 0.1888282
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
typography_spectrum: 0.6783029
name: 'Chrisjroe '
